export { createApolloClient, getApolloClient, ApolloClient, InMemoryCache } from './client';
export * from './queries';
// Re-export generated GraphQL operation types (named exports to avoid conflicts
// with entity types in ./types that share names like City, CurrentWeather, etc.)
export type {
  // Query operation types
  CheckCaseStatusQuery,
  CheckCaseStatusQueryVariables,
  SearchStocksQuery,
  GetStockQuoteQuery,
  GetStockCandlesQuery,
  GetCompanyNewsQuery,
  SearchPodcastsQuery,
  GetTrendingPodcastsQuery,
  GetPodcastEpisodesQuery,
  GetPodcastFeedQuery,
  GetBibleVotdQuery,
  GetBibleVotdApiQuery,
  GetBiblePassageQuery,
  GetBibleVersionsQuery,
  GetCurrentWeatherQuery,
  GetForecastQuery,
  GetHourlyForecastQuery,
  GetWeatherQuery,
  GetAirQualityQuery,
  GetHistoricalWeatherQuery,
  SearchCitiesQuery,
  ReverseGeocodeQuery,
  GetCryptoPricesQuery,
  GetOllamaModelsQuery,
  GetOllamaStatusQuery,
  GetAiUsageSummaryQuery,
  GetAiRecentLogsQuery,
  GetBenchmarkEndpointsQuery,
  GetBenchmarkEndpointModelsQuery,
  GetBenchmarkHistoryQuery,
  GetBenchmarkSummaryQuery,
  GetWorshipSongsListQuery,
  GetWorshipSongsListQueryVariables,
  GetWorshipSongQuery,
  GetWorshipSongQueryVariables,
  // Mutation operation types
  AiChatMutation,
  RunBenchmarkMutation,
  SaveBenchmarkEndpointMutation,
  DeleteBenchmarkEndpointMutation,
  SaveBenchmarkRunMutation,
  AddWorshipSongMutation,
  UpdateWorshipSongMutation,
  DeleteWorshipSongMutation,
  // Subscription operation types
  WeatherUpdatesSubscription,
  // Schema entity types (only those that don't conflict with ./types)
  CaseStatus as GqlCaseStatus,
  CaseStatusHistory as GqlCaseStatusHistory,
  StockSearchResult,
  StockQuote,
  StockCandle,
  CompanyNews,
  BibleVerse,
  BibleVerseItem,
  BiblePassage,
  BibleVersion,
  BenchmarkTimingResult,
  BenchmarkRunResult,
  BenchmarkRun,
  BenchmarkEndpoint,
  BenchmarkSummary,
  PodcastFeed,
  PodcastEpisode,
  PodcastSearchResponse,
  PodcastTrendingResponse,
  PodcastEpisodesResponse,
  AiChatResponse,
  AiAction,
  AiUsageSummary,
  AiDailyStats,
  AiChatLogEntry,
  AiToolCallLog,
  OllamaStatus,
  OllamaRunningModel,
  ToolCallResult,
  Temperature,
  Clouds,
  WeatherData,
  WeatherUpdate,
  WorshipSong as GqlWorshipSong,
  WorshipSongInput,
  WorshipSongUpdateInput,
  // Cloud Files
  GetCloudFilesQuery,
  GetSharedFilesQuery,
  ShareFileMutation,
  ShareFileMutationVariables,
  DeleteFileMutation,
  DeleteFileMutationVariables,
  DeleteSharedFileMutation,
  DeleteSharedFileMutationVariables,
  CloudFile as GqlCloudFile,
  SharedFile as GqlSharedFile,
  // Baby Photos
  GetBabyPhotosQuery,
  DeleteBabyPhotoMutation,
  DeleteBabyPhotoMutationVariables,
  BabyPhoto as GqlBabyPhoto,
  // Digital Library
  GetBooksQuery,
  GetBookChaptersQuery,
  GetBookChaptersQueryVariables,
  GetBookConversionProgressQuery,
  GetBookConversionProgressQueryVariables,
  GetTtsQuotaQuery,
  DeleteBookMutation,
  DeleteBookMutationVariables,
  RestoreBookMutation,
  RestoreBookMutationVariables,
  PermanentDeleteBookMutation,
  PermanentDeleteBookMutationVariables,
  Book as GqlBook,
  BookChapter as GqlBookChapter,
  BookConversionProgress as GqlBookConversionProgress,
  TtsQuota as GqlTtsQuota,
} from './generated';

// Re-export Apollo React hooks so MFEs can import from @mycircle/shared
// instead of @apollo/client/react (which Module Federation doesn't share as a subpath)
export { useQuery, useLazyQuery, useMutation, useSubscription, ApolloProvider } from '@apollo/client/react';
