/** Map from first path segment to i18n key — single source of truth for Breadcrumbs & document titles */
export const ROUTE_LABEL_KEYS: Record<string, string> = {
  weather: 'nav.weather',
  stocks: 'nav.stocks',
  podcasts: 'nav.podcasts',
  ai: 'nav.ai',
  bible: 'nav.bible',
  worship: 'nav.worship',
  notebook: 'nav.notebook',
  baby: 'nav.baby',
  'child-dev': 'nav.childDev',
  english: 'nav.english',
  chinese: 'nav.chinese',
  flashcards: 'nav.flashcards',
  'daily-log': 'nav.dailyLog',
  files: 'nav.cloudFiles',
  'whats-new': 'whatsNew.title',
  immigration: 'nav.immigration',
  benchmark: 'nav.benchmark',
  library: 'nav.digitalLibrary',
  'family-games': 'nav.familyGames',
  'doc-scanner': 'nav.docScanner',
  hiking: 'nav.hikingMap',
  trips: 'nav.tripPlanner',
  polls: 'nav.pollSystem',
  radio: 'nav.radio',
  interview: 'nav.interview',
  transit: 'nav.transit',
  trash: 'nav.recycleBin',
};
