export { useWeatherData } from './useWeatherData';
export { useHistoricalWeather } from './useHistoricalWeather';
export { useAirQuality } from './useAirQuality';
export { useCryptoPrices } from './useCryptoPrices';
export { useUnits } from './useUnits';
export { useRemoteConfig } from './useRemoteConfig';
export { useVerseOfDay } from './useVerseOfDay';
export type { VerseRef } from './useVerseOfDay';
export { useEndpoints } from './useEndpoints';
export type { Endpoint } from './useEndpoints';
export { useChildren, getAgeInMonths, getAgeRemainingDays } from './useChildren';
