/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../ai-assistant/src/**/*.{js,ts,jsx,tsx}",
    "../baby-tracker/src/**/*.{js,ts,jsx,tsx}",
    "../bible-reader/src/**/*.{js,ts,jsx,tsx}",
    "../city-search/src/**/*.{js,ts,jsx,tsx}",
    "../notebook/src/**/*.{js,ts,jsx,tsx}",
    "../podcast-player/src/**/*.{js,ts,jsx,tsx}",
    "../stock-tracker/src/**/*.{js,ts,jsx,tsx}",
    "../weather-display/src/**/*.{js,ts,jsx,tsx}",
    "../worship-songs/src/**/*.{js,ts,jsx,tsx}",
    "../child-development/src/**/*.{js,ts,jsx,tsx}",
    "../flashcards/src/**/*.{js,ts,jsx,tsx}",
    "../daily-log/src/**/*.{js,ts,jsx,tsx}",
    "../cloud-files/src/**/*.{js,ts,jsx,tsx}",
    "../model-benchmark/src/**/*.{js,ts,jsx,tsx}",
    "../immigration-tracker/src/**/*.{js,ts,jsx,tsx}",
    "../digital-library/src/**/*.{js,ts,jsx,tsx}",
    "../family-games/src/**/*.{js,ts,jsx,tsx}",
    "../doc-scanner/src/**/*.{js,ts,jsx,tsx}",
    "../hiking-map/src/**/*.{js,ts,jsx,tsx}",
    "../trip-planner/src/**/*.{js,ts,jsx,tsx}",
    "../poll-system/src/**/*.{js,ts,jsx,tsx}",
    "../radio-station/src/**/*.{js,ts,jsx,tsx}",
    "../ai-interviewer/src/**/*.{js,ts,jsx,tsx}",
    "../transit-tracker/src/**/*.{js,ts,jsx,tsx}",
    "../travel-map/src/**/*.{js,ts,jsx,tsx}",
    "../deal-finder/src/**/*.{js,ts,jsx,tsx}",
    "../web-crawler/src/**/*.{js,ts,jsx,tsx}",
    "../resume-tailor/src/**/*.{js,ts,jsx,tsx}",
    "../setup/src/**/*.{js,ts,jsx,tsx}",
    "../hsa-expenses/src/**/*.{js,ts,jsx,tsx}",
    "../anniversary/src/**/*.{js,ts,jsx,tsx}",
    "../shared/src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.5s ease-out',
      },
    },
  },
  plugins: [],
}
